"""Generate ``docs/coverage_report.md`` from the shipped checkpoint manifests.

The public repo ships an *incomplete* mesh of ``symbol x accuracy`` checkpoints
because the 55 %/75 % legacy runs were pruned before upload. Reviewers cannot
tell from a directory listing alone which cells are intentionally shipped, which
are missing, and which symbols are outside the universe entirely (e.g. TW50
2150 is cited in the paper text but never trained). This script consolidates
that information from the two manifests and the two constituent files.

Usage:
    python scripts/report_coverage.py                    # writes docs/coverage_report.md
    python scripts/report_coverage.py --check            # exit 1 if counts drift

Nothing outside ``docs/`` is written.
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_TW50 = REPO_ROOT / "trained_models" / "manifest.csv"
MANIFEST_DOW30 = REPO_ROOT / "trained_models" / "manifest_dow30.csv"
UNIVERSE_TW50 = REPO_ROOT / "data" / "tw50_2023-12-29.csv"
UNIVERSE_DOW30 = REPO_ROOT / "data" / "dow30_constituents.csv"
OUT = REPO_ROOT / "docs" / "coverage_report.md"

ACCURACIES = (55, 60, 65, 75)


def load_manifest(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def load_tw50_symbols(path: Path) -> list[str]:
    with path.open(encoding="utf-8-sig") as fh:
        rows = list(csv.DictReader(fh))
    # header uses Chinese: 股票代號
    out: list[str] = []
    for r in rows:
        sym = (r.get("股票代號") or r.get("symbol") or "").strip()
        if sym and sym.isdigit():
            out.append(sym)
    return out


def load_dow30_symbols(path: Path) -> list[str]:
    with path.open(encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    return [r["ticker"].strip() for r in rows if r.get("ticker", "").strip()]


def summarize(rows: list[dict[str, str]]) -> tuple[dict[int, int], dict[int, int], list[tuple[str, int]], list[str]]:
    shipped_per_acc: dict[int, int] = {a: 0 for a in ACCURACIES}
    missing_per_acc: dict[int, int] = {a: 0 for a in ACCURACIES}
    missing_pairs: list[tuple[str, int]] = []
    shipped_75_syms: list[str] = []
    for r in rows:
        sym = r["symbol"].strip()
        acc = int(r["window"])
        has_ckpt = bool(r.get("source_ckpt", "").strip())
        if has_ckpt:
            shipped_per_acc[acc] += 1
            if acc == 75:
                shipped_75_syms.append(sym)
        else:
            missing_per_acc[acc] += 1
            missing_pairs.append((sym, acc))
    return shipped_per_acc, missing_per_acc, missing_pairs, shipped_75_syms


def render(
    tw50_rows: list[dict[str, str]],
    dow30_rows: list[dict[str, str]],
    tw50_universe: list[str],
    dow30_universe: list[str],
) -> str:
    tw_ship, tw_miss, tw_missing_pairs, tw_shipped_75 = summarize(tw50_rows)
    dw_ship, dw_miss, dw_missing_pairs, _dw_shipped_75 = summarize(dow30_rows)

    tw_total_ship = sum(tw_ship.values())
    tw_total = tw_total_ship + sum(tw_miss.values())
    dw_total_ship = sum(dw_ship.values())
    dw_total = dw_total_ship + sum(dw_miss.values())

    manifest_syms_tw = sorted({r["symbol"] for r in tw50_rows})
    manifest_syms_dw = sorted({r["symbol"] for r in dow30_rows})
    tw_universe_set = set(tw50_universe)
    dw_universe_set = set(dow30_universe)

    tw_universe_only = sorted(tw_universe_set - set(manifest_syms_tw))
    tw_manifest_only = sorted(set(manifest_syms_tw) - tw_universe_set)
    dw_universe_only = sorted(dw_universe_set - set(manifest_syms_dw))
    dw_manifest_only = sorted(set(manifest_syms_dw) - dw_universe_set)

    lines: list[str] = []
    lines.append("# Checkpoint coverage report\n")
    lines.append(
        "Generated by `scripts/report_coverage.py` from the two shipped manifests "
        "(`trained_models/manifest.csv`, `trained_models/manifest_dow30.csv`) and "
        "the two constituent files (`data/tw50_2023-12-29.csv`, "
        "`data/dow30_constituents.csv`).\n"
    )
    lines.append(
        "The public repo ships an *incomplete* Cartesian product of "
        "`symbol x accuracy`. This report enumerates exactly which cells are "
        "shipped so reviewers can reconcile the numbers against the paper's "
        "Table 4, Figure 5, and Figure 7.\n"
    )

    lines.append("## Executive summary\n")
    lines.append("| Universe | Symbols | Cells (shipped / total) | Per accuracy (55/60/65/75) |")
    lines.append("|---|---|---|---|")
    lines.append(
        f"| TW50 | {len(manifest_syms_tw)} | **{tw_total_ship} / {tw_total}** | "
        f"{tw_ship[55]}/{tw_ship[60]}/{tw_ship[65]}/{tw_ship[75]} |"
    )
    lines.append(
        f"| Dow30 | {len(manifest_syms_dw)} | **{dw_total_ship} / {dw_total}** | "
        f"{dw_ship[55]}/{dw_ship[60]}/{dw_ship[65]}/{dw_ship[75]} |\n"
    )
    lines.append(
        f"**Grand total shipped**: {tw_total_ship + dw_total_ship} of "
        f"{tw_total + dw_total} possible `(symbol, accuracy)` cells.\n"
    )

    lines.append("## Figure 7 (frontier at rho = 75 %) basis\n")
    lines.append(
        "The 75 %-accuracy frontier in Figure 7 is estimated from the "
        f"**{tw_ship[75]} TW50 symbols** and **{dw_ship[75]} Dow30 symbols** that "
        "have a shipped 75 % checkpoint, not the full universe. This is the "
        "reason for the smaller marker cloud at rho = 75 % compared with lower "
        "accuracies.\n"
    )
    lines.append(
        f"TW50 symbols with a 75 % checkpoint ({len(tw_shipped_75)}): "
        + ", ".join(f"`{s}`" for s in sorted(tw_shipped_75))
        + "\n"
    )

    lines.append("## Known omissions (documented, not bugs)\n")
    lines.append(
        "- **TW50 symbol 2150 (崇越電)**: cited in the paper narrative but not "
        "present in `data/tw50_2023-12-29.csv`. It was excluded from the "
        f"experiment universe (universe size N = {len(tw50_universe)}) and "
        "therefore has no checkpoint. Update paper Table 4 caption to state "
        "\"N = 50 constituents, 2150 excluded\".\n"
    )

    lines.append("## Missing checkpoints\n")
    lines.append(
        f"TW50: {sum(tw_miss.values())} cells marked `MISSING legacy checkpoint`. "
        f"Dow30: {sum(dw_miss.values())} cells (all at rho = 55 %).\n"
    )

    lines.append("### TW50 missing pairs\n")
    lines.append("| Accuracy | Count | Symbols |")
    lines.append("|---:|---:|---|")
    for acc in ACCURACIES:
        pairs = sorted(s for s, a in tw_missing_pairs if a == acc)
        cell = ", ".join(f"`{s}`" for s in pairs) if pairs else "(none)"
        lines.append(f"| {acc} % | {len(pairs)} | {cell} |")
    lines.append("")

    lines.append("### Dow30 missing pairs\n")
    lines.append("| Accuracy | Count | Symbols |")
    lines.append("|---:|---:|---|")
    for acc in ACCURACIES:
        pairs = sorted(s for s, a in dw_missing_pairs if a == acc)
        cell = ", ".join(f"`{s}`" for s in pairs) if pairs else "(none)"
        lines.append(f"| {acc} % | {len(pairs)} | {cell} |")
    lines.append("")

    lines.append("## Consistency cross-check\n")
    lines.append(
        f"- TW50 manifest lists {len(manifest_syms_tw)} distinct symbols; "
        f"universe file lists {len(tw50_universe)}."
    )
    if tw_universe_only or tw_manifest_only:
        if tw_universe_only:
            lines.append(
                "  - In universe but not in manifest: "
                + ", ".join(f"`{s}`" for s in tw_universe_only)
            )
        if tw_manifest_only:
            lines.append(
                "  - In manifest but not in universe: "
                + ", ".join(f"`{s}`" for s in tw_manifest_only)
            )
    else:
        lines.append("  - Both sets agree.")
    lines.append(
        f"- Dow30 manifest lists {len(manifest_syms_dw)} distinct symbols; "
        f"universe file lists {len(dow30_universe)}."
    )
    if dw_universe_only or dw_manifest_only:
        if dw_universe_only:
            lines.append(
                "  - In universe but not in manifest: "
                + ", ".join(f"`{s}`" for s in dw_universe_only)
            )
        if dw_manifest_only:
            lines.append(
                "  - In manifest but not in universe: "
                + ", ".join(f"`{s}`" for s in dw_manifest_only)
            )
    else:
        lines.append("  - Both sets agree.")
    lines.append("")

    lines.append("## Regenerate this report\n")
    lines.append("```")
    lines.append("python scripts/report_coverage.py")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true",
                   help="Regenerate in-memory and diff against the on-disk report; "
                        "exit 1 if they differ (useful in CI).")
    args = p.parse_args(argv)

    tw50_rows = load_manifest(MANIFEST_TW50)
    dow30_rows = load_manifest(MANIFEST_DOW30)
    tw50_universe = load_tw50_symbols(UNIVERSE_TW50)
    dow30_universe = load_dow30_symbols(UNIVERSE_DOW30)
    new_body = render(tw50_rows, dow30_rows, tw50_universe, dow30_universe)

    if args.check:
        if not OUT.exists():
            print(f"[FAIL] {OUT} does not exist; run without --check to create it.")
            return 1
        old = OUT.read_text(encoding="utf-8")
        if old != new_body:
            print(f"[FAIL] {OUT} is stale; regenerate with `python scripts/report_coverage.py`.")
            return 1
        print(f"[OK] {OUT} is up to date.")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(new_body, encoding="utf-8")
    print(f"[OK] wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
